version: '3.8'

services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbt-abt:latest
    container_name: dbt
    volumes:
      - shared_volume:/shared_volume      # współdzielony dostęp do danych z Parquet
      - .:/app                            # montuje lokalny projekt
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  shared_volume:
    name: shared_volume