version: '3.8'

services:
  dbt:
    build: .
    container_name: dbt
    volumes:
      - ./models:/usr/app/models
      - ./macros:/usr/app/macros
      - ./seeds:/usr/app/seeds
      - ./profiles.yml:/root/.dbt/profiles.yml:ro
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
