version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-env
    ports:
      - "8443:8443"   # Code Server UI
    volumes:
      - .:/app        # Mount project directory
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - PASSWORD=abc   # Password for code-server login
    restart: unless-stopped