version: "3.8"

services:
  data-platform:
    build: ./services/data-platform
    container_name: Formula1_020
    volumes:
      - ./layers:/workspace/layers
    environment:
      # ADLS credentials (ustaw w .env lub tutaj)
      AZURE_STORAGE_ACCOUNT: your_account_name
      AZURE_TENANT_ID: your_tenant_id
      AZURE_CLIENT_ID: your_client_id
      AZURE_CLIENT_SECRET: your_client_secret
      DBT_PROFILES_DIR: /workspace/.dbt
    working_dir: /workspace
    command: sleep infinity
    networks:
      - dpl-network

  code-server:
    build: ./services/code-server
    container_name: code-server
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
    environment:
      PASSWORD: "changeme"    # zmień na silne hasło
    networks:
      - dpl-network

networks:
  dpl-network:
    driver: bridge
